[datalake]
region = "us-east-1"
bucket_name = "my-company-data-lake"
glue_database = "analytics_catalog"
raw_prefix = "raw/"
processed_prefix = "curated/"
analytics_prefix = "analytics/"
kms_key_id = "arn:aws:kms:us-east-1:123456789012:key/example"
crawler_name = "raw-zone-crawler"
crawler_role_arn = "arn:aws:iam::123456789012:role/GlueCrawlerRole"
crawler_schedule = "cron(0 6 * * ? *)"
athena_workgroup = "lakehouse-workgroup"

[datalake.tags]
Environment = "dev"
Owner = "data-eng"
